name: First Workflow

on:
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying branch ${{ github.ref }}"
      
      - name: The job has failed
        if: ${{ failure() }}
        run: echo "failed"

      - name: Set color
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"

      - name: Get color
        run: echo "${{ step.color-generator.outputs.SELECTED_COLOR }}"

      - name: Set a value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV

      - run: |
          echo "${{ env.action_state }}"
